POST https://apidemo.iut-bm.univ-fcomte.fr/herocorp/heroes/create/
content-type: application/json

{
  "publicName": "pipi sss",
  "realName": "opopo",
  "power": [
    {
      "name": "ssss",
      "type": "ssss",
      "level": 100
    }
  ]
}