PUT https://apidemo.iut-bm.univ-fcomte.fr/herocorp/heroes/update
content-type: application/json
org-secret: 0000

{
  "_id": "6658d9a9069cfbf448c0ae74",
  "publicName": "pp",
  "realName": "pp",
  "powers": [
    {
      "name": "pp",
      "type": "pp",
      "level": "1"
    }
  ]
}