PUT https://apidemo.iut-bm.univ-fcomte.fr/herocorp/heroes/authupdate
content-type: application/json
x-xsrf-token: bf9324a2-3a49-473d-a311-ad8ca259253b

{
  "_id": "614ddafcfda4c31dc9299352",
  "publicName": "super dupond",
  "realName": "jean dupondszszs",
  "powers": [
    {
      "name": "super biscottos",
      "type": 2,
      "level": 77,
      "_id": "614ddafcfda4c31dc9299353"
    },
    {
      "name": "test ajout",
      "type": 1,
      "level": 1,
      "_id": "665c8207069cfbf448c0d00b"
    }
  ]
}